### ISSUE TITLE
How i can do multiline line chart with react version ?

### ISSUE THREAD

**Issue by lawlessnut** [AnyChart/AnyChart-React#1]
const lineData = [
{ name : "mon" ,  x:20, y:20},
{ name : "tue" ,  x:10, y:20},
{ name : "wed" , x:10, y:20},
{ name : "thu" , x:10, y:20},
{ name : "fri" ,  x:10, y:20},
{ name : "sat" , x:10, y:20},
{ name : "sun" , x:10, y:20},
]
`<AnyChart height={400} id="pvtId"
                       data={lineData}
                       type="line" title="P v T" />`

**Comment by chidori** [comment]
First of all you should prepare your data for series.
```
const multilineData = [
  ["Point 1", 4, 2],
  ["Point 2", 5, 3],
  ["Point 3", 3, 5]
];
```
or as object
```
const multilineData = [
  {x: "Point 1", value1: 4, value2: 2},
  {x: "Point 2", value1: 5, value2: 3},
  {x: "Point 3", value1: 3, value2: 5}
];
```
This data describes 2 series with 3 categories.
After that render chart with your settings:
`<AnyChart height={400} id="pvtId" type="line" title="P v T" />`
And re-render it with your data:
`<AnyChart data={multilineData} />`
