### ISSUE TITLE
Strange component behavior

### ISSUE THREAD

**Issue by BEGEMOT9I** [AnyChart/AnyChart-React#11]
Hi. I conduct a comparative analysis of visualization tools and one of the tools on my list is AnyChart. Since I use React adapters whenever possible, I also took your implementation. But I ran into one very strange problem. It consists in the fact that if it is necessary to draw a dataset from several series, I have to draw an adapter component with the initial settings without a dataset and when redrawing (re-rendering) already set it. For example:
```typescript
interface Props {}
interface State {
  isMounted: boolean
}

const dataset = [
  ['2018', 1, 2, 3],
  ['2017', 10, 20, 30],
  ['2016', 100, 200, 300],
]

class LineChart extends PureComponent<Props, State> {
  public static displayName = 'LineChart'
  public state: State = {
    isMounted: false
  }

  componentDidMount() {
    this.setState({ isMounted: true })
  }

  public render() {
    const { width, height } = this.props

    if (this.state.isMounted) {
      const chartDataSet = anychart.data.set(dataset)

      return <AnyChart data={chartDataSet} />
    }

    return <AnyChart width={width} height={height} type="line" legend />
  }
}
```
I analyzed the adapter code a bit and paid attention to this part:
```jsx
  // ...
  createInstance(props) {
    if (props.instance) {
      // ...
    } else if (props.type) {
      this.removeInstance();
      this.disposeInstance = true;
      this.instance = anychart[props.type](props.data);
      this.isStage = false;
      delete props.type;
      delete props.data;
    }
    // ...
  }
  // ...
```
I understand that, for example, the method `anychart.line` and the method `chart.data` take different input parameters. Does it make sense to separate these two properties and rename at least one of them at least in the adapter, so that there is no need to re-render the chart?

**Comment by Shestac92** [comment]
@BEGEMOT9I 
This plugin was designed a while ago so it can require some optimizations. We will look into it and consider your report. Thank you for your report!

**Comment by BEGEMOT9I** [comment]
Thank you too.
