### ISSUE TITLE
Cannot render multi-series chart

### ISSUE THREAD

**Issue by jimmy-e** [AnyChart/AnyChart-React#12]
**Reproduce:**
* Clone [this repo](https://github.com/jimmy-e/anychart-multiseries).
* Run `yarn`
* Run `yarn build:dev`
* Run `yarn start`
* Open your browser to `http://localhost:8080/`

**Issue:**
The multi-series chart does not show up. As mentioned [here](https://github.com/AnyChart/AnyChart-React/blob/master/examples/src/multiseries_column_chart.js), the chart needs to be re-rendered to render the multi-column data. However, this does not seem feasible for the example repo, if the chart is part of a nested child component that cannot be directly re-rendered using the `react-dom`. (Using `react-dom` to render components more than once in the react spa is considered an anti-pattern).

**Question:**
How can we render a mutli-series chart when using a nested react component?

**Comment by Shestac92** [comment]
@jimmy-e 
In your case, there's no need to rerender the chart. You can create the multi-series chart in a single rendering.
The plugin supports an approach of applying chart instance. It means that you can create the chart using the default library API and then apply the chart instance to the AnyChart React plugin. For details, check [the sample](https://github.com/AnyChart/AnyChart-React/blob/master/examples/src/stock.js).

**Comment by jimmy-e** [comment]
@Shestac92 , thanks. Is there any way to  only way to create a multi-series chart in a single rendering via react props, as [seen here](https://github.com/AnyChart/AnyChart-React/blob/master/examples/src/chart_with_json.js), or are we limited to the default api and class methods? Thanks.

**Comment by jimmy-e** [comment]
@Shestac92 , closing this ticket. [Using JSON configurations as well seems pretty satisfactory](https://docs.anychart.com/Working_with_Data/Data_From_JSON).
