### ISSUE TITLE
How to get the coordinates of a rectangle that is drawn freely using the plot.annotations () function. StartDrawing ('rectangle')?

### ISSUE THREAD

**Issue by Nikrokss** [AnyChart/AnyChart-React#20]
Hello everyone, please help me get the coordinates of the drawn rectangle (I created it using plot.annotations (). StartDrawing ('rectangle')) on the trading chart

![Screenshot at Nov 05 11-21-31](https://user-images.githubusercontent.com/44313407/140718957-41e0c352-cc34-4beb-8e39-2a4fb402f627.png)

**Comment by Shestac92** [comment]
@Nikrokss 
Do you need coordinates in pixels or xAnchors and valueAnchors (respective values on scales) of the annotation?

**Comment by Nikrokss** [comment]
@Shestac92
I need both of these values

**Comment by Shestac92** [comment]
@Nikrokss 
You can achieve that using the library API. For details, check [the sample](https://playground.anychart.com/WjLEPPZD/0).

**Comment by Nikrokss** [comment]
@Shestac92 Thank you very much for your help
