### ISSUE TITLE
Tag Cloud

### ISSUE THREAD

**Issue by brentadamson** [AnyChart/AnyChart-React#21]
Hi,

How do I create a tag cloud with this library? I've tried the following but get errors: 

```
<AnyChart
      type="tag cloud"
      data={"this is a string string blah string"}
  />
```

The error:
```
Uncaught TypeError: anychart[e.type] is not a function
```

I've also tried several variations like `tagCloud`, etc with no luck. Other chart types work. Is a tag cloud like the following not supported? https://www.anychart.com/products/anychart/gallery/Tag_Cloud/The_Old_Man_and_the_Sea.php

**Comment by Shestac92** [comment]
@brentadamson 
We recommend using the `instance` attribute. Here is [the sample](https://codesandbox.io/s/react-example-forked-8jj5i).

**Comment by brentadamson** [comment]
Great! Thanks!
