### ISSUE TITLE
setting minimum and maximum for yScale

### ISSUE THREAD

**Issue by rivyx** [AnyChart/AnyChart-React#3]
Hi,

I'm trying to set to the minimum and maximum bounds for the yScale and am having trouble. Here's my component.

`<AnyChart key={i}
										id={'anychart-bar-'+i}
										type='bar'
										height={300}
										data={data}
										yScale={{
											minimum: -2,
											maximum: 2
										}}
										yAxis={[0,
											{
												labels: {
													format: x => x.value + 1
												}
											}
										]}
										xAxis={[0,
											{
												orientation: 'right',
												overlapMode: 'allowOverlap'
											}
										]}
										tooltip={{
											format: x => x.value + 1
										}}
									/>`

However, the value ranges on the y axis are still being set automatically by the data.

**Comment by Alexeypashkan** [comment]
Unfortunately, the yScale can’t be set by object
To solve this problem, you need to create the Scale instance and set it up.

Here is a workaround. And your code should look like this

const yScale = anychart.scales.linear().minimum(-2).maximum(2)
<AnyChart key={i} id={'anychart-bar-'+i}
          type='bar'
          height={300}
          data={data} yScale={yScale}
          yAxis={[0, { labels: { format: x => x.value + 1 } } ]}
          xAxis={[0, { orientation: 'right', overlapMode: 'allowOverlap' } ]}
          tooltip={{ format: x => x.value + 1 }}/>

**Comment by loki20beta** [comment]
@rivyx with the release of version 8 you can set scales from the component code.
