### ISSUE TITLE
How do I prevent rescrolling

### ISSUE THREAD

**Issue by Radzell** [AnyChart/AnyChart-React#9]
How do I prevent a scrolling when my data changes?

```
chart.data(treeData);

<AnyChart
   instance={stage}
  height={600}
  charts={[chart]} />
```

**Comment by Shestac92** [comment]
@Radzell 
Please, can you specify which chart type you are using?
Is your chart is scrolled to a specific position before the chart data updates?

**Comment by Radzell** [comment]
@Shestac92 I am using a gantt project chart. It's rescrolling back to the beginning of the chart. The scroll happens when I update the data.

**Comment by Shestac92** [comment]
@Radzell 
If you add new items to the existing tree data it doesn't lead to dropping the current scrolling position. [Here is a sample](https://playground.anychart.com/Lfd6j0M0/2) how it works.

If you apply new data tree to the chart it leads to dropping of the current scroll position as the currently visible range cannot cover the new data range. You can avoid this by using the following approach. Before updating the chart you can save the current visible range, update the chart and then zoom to that range again. [Here is a sample](https://playground.anychart.com/A2mWLFaZ) of this approach.
